export const routers = {
    login: "/login",
    forgot: "/forgot",
    profile: "/profile",
    changePassword: "/password/change",
    home: "/home",
    roles: "/roles/list",
    rolesAdd: "/roles/add",
    rolesEdit: "/roles/edit/:id",
    subAdminList: "/sub-admin",
    subAdminEdit: "/sub-admin/edit/:id",
    subAdminAdd: "/sub-admin/add",
    taxList: "/tax",
    taxAdd: "/tax/add",
    taxEdit: "/tax/edit/:id",
    idList: "/id",
    idAdd: "/id/add",
    idEdit: "/id/edit/:id",
    membershipList: "/membership",
    membershipAdd: "/membership/add",
    membershipEdit: "/membership/edit/:id",
    reportItemSaleByStore: "/report/item-sale/by-store",
    reportItemSaleByTodayStore: "/report/required/itemlist/today/store/:id",
    reportTotalItemSalesLast30Days: "/report/total-item-sales/last-30-days",
    reportOrder: "/report/order",
    reportTax: "/report/tax",
    notificationToDriver: "/notification/to-driver",
    notificationToStore: "/notification/to-store",
    notificationToUser: "/notification/to-user",
    notificationListDriver: "/notification/list/driver",
    notificationListStore: "/notification/list/store",
    notificationListUser: "/notification/list/user",
    userList: "/user/list",
    userEdit: "/user/edit/:id",
    userDetail: "/user/detail/:id",
    usersWalletRechargeHistory: "/users/wallet-recharge-history",
    categoryList: "/category/list",
    categoryAdd: "/category/add",
    categoryEdit: "/category/edit/:id",
    subCategoryList: "/sub-category/list",
    subCategoryAdd: "/sub-category/add",
    subCategoryEdit: "/sub-category/edit/:id",
    productList: "/product/list",
    productAdd: "/product/add",
    productEdit: "/product/edit/:id",
    productVariant: "/product/Variant/:id",
    productVariantEdit: "/product/Variant/edit/:id",
    productVariantAdd: "/product/Variant/add/:id",
    bulkUpload: "/bulk/upload",
    trendingSearchProductAdd: "/trending-search/product/add",
    storeProductsList: "/store-data/list",
    societyList: "/society/list",
    societyAdd: "/society/add",
    societyEdit: "/society/edit/:id",
    areaBulkUploadCitySociety: "/area-bulk-upload/city-society",
    cityList: "/city/list",
    cityAdd: "/city/add",
    cityEdit: "/city/edit/:id",
    storesWaitingForApprovalStoreList: "/stores/waiting-for-approval/store/list",
    storesFinance: "/stores/finance",
    adminStoreList: "/admin/store/list",
    adminStoreOrders: "/admin/store/orders/:id",
    adminStoreAdd: "/admin/store/add",
    adminStoreEdit: "/admin/store/edit/:id",
    adminAllOrders: "/admin/all-orders",
    adminCancelledOrders: "/admin/cancelled/orders",
    adminCompleteOrders: "/admin/complete-orders",
    adminOngoingOrders: "/admin/ongoing-orders",
    adminOutForDeliveryOrders: "/admin/out-for-delivery-orders",
    adminPaymentFailedOrders: "/admin/payment-failed-orders",
    adminPendingOrders: "/admin/pending-orders",
    ordersTodayAll: "/orders/today/all",
    storeMissedOrders: "/store/missed/orders",
    cancelledOrders: "/cancelled/orders",
    payoutReq: "/payout-req",
    prv: "/prv",
    redeem: "/redeem",
    reward: "/reward",
    rewardAdd: "/reward/add",
    rewardEdit: "/reward/edit/:id",
    dBoyList: "/d-boy/list",
    dBoyAdd: "/d-boy/add",
    dBoyEdit: "/d-boy/edit/:id",
    dBoyOrder: "/d-boy/orders/:id",
    dBoyIncentive: "/d-boy-incentive",
    aboutUs: "/about-us",
    terms: "/terms",
    driverFeedbackList: "/driver-feedback/list",
    storeFeedbackList: "/store-feedback/list",
    userFeedbackList: "/user-feedback/list",
    driverCallbackRequests: "/driver-callback-requests",
    storeCallbackRequests: "/store-callback-requests",
    userCallbackRequests: "/user-callback-requests",
    globalSetting: "/global-setting",
    cancellingReasonsList: "/cancelling-reasons/list",
    cancellingReasonsAdd: "/cancelling-reasons/add",
    cancellingReasonsEdit: "/cancelling-reasons/edit/:id",
};

export const languages = ["English", "Bulgarian", "Hindi", "Chinese"];

export const tabs = {
    navigation: {
        [languages[0]]: "Navigation",
        [languages[1]]: "Навигация",
        [languages[2]]: "नेविगेशन",
        [languages[3]]: "Dashboard"
    },
    dashboard: {
        [languages[0]]: "Dashboard",
        [languages[1]]: "Табло за управление",
        [languages[2]]: "Dashboard",
        [languages[3]]: "Dashboard"
    },
    subAdminManagement: {
        [languages[0]]: "Sub-Admin Management",
        [languages[1]]: "Sub-Admin Management",
        [languages[2]]: "Sub-Admin Management",
        [languages[3]]: "Sub-Admin Management",
    },
    roles: {[languages[0]]: "Roles", [languages[1]]: "Roles", [languages[2]]: "Roles", [languages[3]]: "Roles",},
    subAdminList: {
        [languages[0]]: "Sub-Admin",
        [languages[1]]: "Sub-Admin",
        [languages[2]]: "Sub-Admin",
        [languages[3]]: "Sub-Admin",
    },
    taxList: {[languages[0]]: "Taxes", [languages[1]]: "Taxes", [languages[2]]: "Taxes", [languages[3]]: "Taxes",},
    idList: {[languages[0]]: "ID", [languages[1]]: "ID", [languages[2]]: "ID", [languages[3]]: "ID",},
    membershipList: {
        [languages[0]]: "Membership Plans",
        [languages[1]]: "Membership Plans",
        [languages[2]]: "Membership Plans",
        [languages[3]]: "Membership Plans",
    },
    reports: {
        [languages[0]]: "Reports",
        [languages[1]]: "Reports",
        [languages[2]]: "Reports",
        [languages[3]]: "Reports",
    },
    reportItemSaleByStore: {
        [languages[0]]: "Item Requirement(Day-Wise)",
        [languages[1]]: "Item Requirement(Day-Wise)",
        [languages[2]]: "Item Requirement(Day-Wise)",
        [languages[3]]: "Item Requirement(Day-Wise)",
    },
    reportTotalItemSalesLast30Days: {
        [languages[0]]: "Item Sales Report(Last 30 Days)",
        [languages[1]]: "Item Sales Report(Last 30 Days)",
        [languages[2]]: "Item Sales Report(Last 30 Days)",
        [languages[3]]: "Item Sales Report(Last 30 Days)",
    },
    reportOrder: {
        [languages[0]]: "Reports",
        [languages[1]]: "Reports",
        [languages[2]]: "Reports",
        [languages[3]]: "Reports",
    },
    reportTax: {
        [languages[0]]: "Tax Reports",
        [languages[1]]: "Dashboard",
        [languages[2]]: "Dashboard",
        [languages[3]]: "Dashboard"
    },
    sendNotifications: {
        [languages[0]]: "Send Notifications",
        [languages[1]]: "Send Notifications",
        [languages[2]]: "Send Notifications",
        [languages[3]]: "Send Notifications",
    },
    notificationToDriver: {
        [languages[0]]: "Send Notification to Drivers",
        [languages[1]]: "Send Notification to Drivers",
        [languages[2]]: "Send Notification to Drivers",
        [languages[3]]: "Send Notification to Drivers",
    },
    notificationToStore: {
        [languages[0]]: "Send Notification to Store",
        [languages[1]]: "Send Notification to Store",
        [languages[2]]: "Send Notification to Store",
        [languages[3]]: "Send Notification to Store",
    },
    notificationToUser: {
        [languages[0]]: "Send Notification to Users",
        [languages[1]]: "Send Notification to Users",
        [languages[2]]: "Send Notification to Users",
        [languages[3]]: "Send Notification to Users",
    },
    listNotifications: {
        [languages[0]]: "List Notifications",
        [languages[1]]: "List Notifications",
        [languages[2]]: "List Notifications",
        [languages[3]]: "List Notifications",
    },
    notificationListDriver: {
        [languages[0]]: "Driver Notifications",
        [languages[1]]: "Driver Notifications",
        [languages[2]]: "Driver Notifications",
        [languages[3]]: "Driver Notifications",
    },
    notificationListStore: {
        [languages[0]]: "Store Notifications",
        [languages[1]]: "Store Notifications",
        [languages[2]]: "Store Notifications",
        [languages[3]]: "Store Notifications",
    },
    notificationListUser: {
        [languages[0]]: "User Notifications",
        [languages[1]]: "User Notifications",
        [languages[2]]: "User Notifications",
        [languages[3]]: "User Notifications",
    },
    userManagement: {
        [languages[0]]: "Users Management",
        [languages[1]]: "Users Management",
        [languages[2]]: "Users Management",
        [languages[3]]: "Users Management",
    },
    userList: {
        [languages[0]]: "Users Data",
        [languages[1]]: "Users Data",
        [languages[2]]: "Users Data",
        [languages[3]]: "Users Data",
    },
    usersWalletRechargeHistory: {
        [languages[0]]: "Wallet Recharge History",
        [languages[1]]: "Wallet Recharge History",
        [languages[2]]: "Wallet Recharge History",
        [languages[3]]: "Wallet Recharge History",
    },
    categoryManagement: {
        [languages[0]]: "Category Management",
        [languages[1]]: "Category Management",
        [languages[2]]: "Category Management",
        [languages[3]]: "Category Management",
    },
    categoryList: {
        [languages[0]]: "Parent Categories",
        [languages[1]]: "Parent Categories",
        [languages[2]]: "Parent Categories",
        [languages[3]]: "Parent Categories",
    },
    subCategoryList: {
        [languages[0]]: "Sub Categories",
        [languages[1]]: "Sub Categories",
        [languages[2]]: "Sub Categories",
        [languages[3]]: "Sub Categories",
    },
    productCatalog: {
        [languages[0]]: "Product Catalog",
        [languages[1]]: "Product Catalog",
        [languages[2]]: "Product Catalog",
        [languages[3]]: "Product Catalog",
    },
    productList: {
        [languages[0]]: "Admin Products",
        [languages[1]]: "Admin Products",
        [languages[2]]: "Admin Products",
        [languages[3]]: "Admin Products",
    },
    bulkUpload: {
        [languages[0]]: "Bulk Upload",
        [languages[1]]: "Bulk Upload",
        [languages[2]]: "Bulk Upload",
        [languages[3]]: "Bulk Upload",
    },
    trendingSearchProductAdd: {
        [languages[0]]: "Trending Search",
        [languages[1]]: "Trending Search",
        [languages[2]]: "Trending Search",
        [languages[3]]: "Trending Search",
    },
    storeProductsList: {
        [languages[0]]: "Store Products(request)",
        [languages[1]]: "Store Products(request)",
        [languages[2]]: "Store Products(request)",
        [languages[3]]: "Store Products(request)",
    },
    areaManagement: {
        [languages[0]]: "Area Management",
        [languages[1]]: "Area Management",
        [languages[2]]: "Area Management",
        [languages[3]]: "Area Management",
    },
    societyList: {
        [languages[0]]: "Area/Society",
        [languages[1]]: "Area/Society",
        [languages[2]]: "Area/Society",
        [languages[3]]: "Area/Society",
    },
    areaBulkUploadCitySociety: {
        [languages[0]]: "Bulk Upload",
        [languages[1]]: "Bulk Upload",
        [languages[2]]: "Bulk Upload",
        [languages[3]]: "Bulk Upload",
    },
    cityList: {[languages[0]]: "Cities", [languages[1]]: "Cities", [languages[2]]: "Cities", [languages[3]]: "Cities",},
    storeManagement: {
        [languages[0]]: "Store Management",
        [languages[1]]: "Store Management",
        [languages[2]]: "Store Management",
        [languages[3]]: "Store Management",
    },
    storesWaitingForApprovalStoreList: {
        [languages[0]]: "Store ApprovalStore Approval",
        [languages[1]]: "Store ApprovalStore Approval",
        [languages[2]]: "Store ApprovalStore Approval",
        [languages[3]]: "Store ApprovalStore Approval",
    },
    storesFinance: {
        [languages[0]]: "Store Earning/Payments",
        [languages[1]]: "Store Earning/Payments",
        [languages[2]]: "Store Earning/Payments",
        [languages[3]]: "Store Earning/Payments",
    },
    adminStoreList: {
        [languages[0]]: "Store List",
        [languages[1]]: "Store List",
        [languages[2]]: "Store List",
        [languages[3]]: "Store List",
    },
    ordersManagement: {
        [languages[0]]: "Orders Management",
        [languages[1]]: "Orders Management",
        [languages[2]]: "Orders Management",
        [languages[3]]: "Orders Management",
    },
    adminAllOrders: {
        [languages[0]]: "All Orders",
        [languages[1]]: "All Orders",
        [languages[2]]: "All Orders",
        [languages[3]]: "All Orders",
    },
    adminCancelledOrders: {
        [languages[0]]: "Cancelled Orders",
        [languages[1]]: "Cancelled Orders",
        [languages[2]]: "Cancelled Orders",
        [languages[3]]: "Cancelled Orders",
    },
    adminCompleteOrders: {
        [languages[0]]: "Completed Orders",
        [languages[1]]: "Completed Orders",
        [languages[2]]: "Completed Orders",
        [languages[3]]: "Completed Orders",
    },
    adminOngoingOrders: {
        [languages[0]]: "Ongoing Orders",
        [languages[1]]: "Ongoing Orders",
        [languages[2]]: "Ongoing Orders",
        [languages[3]]: "Ongoing Orders",
    },
    adminOutForDeliveryOrders: {
        [languages[0]]: "Out For Delivery Orders",
        [languages[1]]: "Out For Delivery Orders",
        [languages[2]]: "Out For Delivery Orders",
        [languages[3]]: "Out For Delivery Orders",
    },
    adminPaymentFailedOrders: {
        [languages[0]]: "Payment Failed Orders",
        [languages[1]]: "Payment Failed Orders",
        [languages[2]]: "Payment Failed Orders",
        [languages[3]]: "Payment Failed Orders",
    },
    adminPendingOrders: {
        [languages[0]]: "Pending Orders",
        [languages[1]]: "Pending Orders",
        [languages[2]]: "Pending Orders",
        [languages[3]]: "Pending Orders",
    },
    ordersTodayAll: {
        [languages[0]]: "Day Wise Orders",
        [languages[1]]: "Day Wise Orders",
        [languages[2]]: "Day Wise Orders",
        [languages[3]]: "Day Wise Orders",
    },
    storeMissedOrders: {
        [languages[0]]: "Missed Orders",
        [languages[1]]: "Missed Orders",
        [languages[2]]: "Missed Orders",
        [languages[3]]: "Missed Orders",
    },
    cancelledOrders: {
        [languages[0]]: "Reject By Store",
        [languages[1]]: "Reject By Store",
        [languages[2]]: "Reject By Store",
        [languages[3]]: "Reject By Store",
    },
    payout: {[languages[0]]: "Payout", [languages[1]]: "Payout", [languages[2]]: "Payout", [languages[3]]: "Payout",},
    payoutReq: {
        [languages[0]]: "Payout Requests",
        [languages[1]]: "Payout Requests",
        [languages[2]]: "Payout Requests",
        [languages[3]]: "Payout Requests",
    },
    prv: {
        [languages[0]]: "Payout Validation",
        [languages[1]]: "Payout Validation",
        [languages[2]]: "Payout Validation",
        [languages[3]]: "Payout Validation",
    },
    rewardManage: {
        [languages[0]]: "Rewards",
        [languages[1]]: "Rewards",
        [languages[2]]: "Rewards",
        [languages[3]]: "Rewards",
    },
    redeem: {
        [languages[0]]: "Redeem Value",
        [languages[1]]: "Redeem Value",
        [languages[2]]: "Redeem Value",
        [languages[3]]: "Redeem Value",
    },
    reward: {
        [languages[0]]: "Rewards",
        [languages[1]]: "Rewards",
        [languages[2]]: "Rewards",
        [languages[3]]: "Rewards",
    },
    deliveryBoy: {
        [languages[0]]: "Delivery Boy",
        [languages[1]]: "Delivery Boy",
        [languages[2]]: "Delivery Boy",
        [languages[3]]: "Delivery Boy",
    },
    dBoyList: {
        [languages[0]]: "Delivery Boy",
        [languages[1]]: "Delivery Boy",
        [languages[2]]: "Delivery Boy",
        [languages[3]]: "Delivery Boy",
    },
    dBoyIncentive: {
        [languages[0]]: "Delivery Boy Incentive",
        [languages[1]]: "Delivery Boy Incentive",
        [languages[2]]: "Delivery Boy Incentive",
        [languages[3]]: "Delivery Boy Incentive",
    },
    pages: {[languages[0]]: "Pages", [languages[1]]: "Pages", [languages[2]]: "Pages", [languages[3]]: "Pages",},
    aboutUs: {
        [languages[0]]: "About Us",
        [languages[1]]: "About Us",
        [languages[2]]: "About Us",
        [languages[3]]: "About Us",
    },
    terms: {
        [languages[0]]: "Terms & Conditions",
        [languages[1]]: "Terms & Conditions",
        [languages[2]]: "Terms & Conditions",
        [languages[3]]: "Terms & Conditions",
    },
    feedback: {
        [languages[0]]: "Feedback",
        [languages[1]]: "Feedback",
        [languages[2]]: "Feedback",
        [languages[3]]: "Feedback",
    },
    driverFeedbackList: {
        [languages[0]]: "Delivery Boy Feedback",
        [languages[1]]: "Delivery Boy Feedback",
        [languages[2]]: "Delivery Boy Feedback",
        [languages[3]]: "Delivery Boy Feedback",
    },
    storeFeedbackList: {
        [languages[0]]: "Store Feedback",
        [languages[1]]: "Store Feedback",
        [languages[2]]: "Store Feedback",
        [languages[3]]: "Store Feedback",
    },
    userFeedbackList: {
        [languages[0]]: "Users Feedback",
        [languages[1]]: "Users Feedback",
        [languages[2]]: "Users Feedback",
        [languages[3]]: "Users Feedback",
    },
    callbackRequests: {
        [languages[0]]: "Callback Requests",
        [languages[1]]: "Callback Requests",
        [languages[2]]: "Callback Requests",
        [languages[3]]: "Callback Requests",
    },
    driverCallbackRequests: {
        [languages[0]]: "Delivery Boy Callback Requests",
        [languages[1]]: "Delivery Boy Callback Requests",
        [languages[2]]: "Delivery Boy Callback Requests",
        [languages[3]]: "Delivery Boy Callback Requests",
    },
    storeCallbackRequests: {
        [languages[0]]: "Stores Callback Requests",
        [languages[1]]: "Stores Callback Requests",
        [languages[2]]: "Stores Callback Requests",
        [languages[3]]: "Stores Callback Requests",
    },
    userCallbackRequests: {
        [languages[0]]: "Users Callback Requests",
        [languages[1]]: "Users Callback Requests",
        [languages[2]]: "Users Callback Requests",
        [languages[3]]: "Users Callback Requests",
    },
    globalSetting: {
        [languages[0]]: "Settings",
        [languages[1]]: "Settings",
        [languages[2]]: "Settings",
        [languages[3]]: "Settings",
    },
    cancellingReasonsList: {
        [languages[0]]: "Cancelling Reasons",
        [languages[1]]: "Cancelling Reasons",
        [languages[2]]: "Cancelling Reasons",
        [languages[3]]: "Cancelling Reasons",
    }
};

export const buttonType = {
    edit: "edit",
    layer: "layer",
    editForVariant: "editForVariant",
    delete: "delete",
    process: "process",
    reject: "reject",
    assignStore: "assignStore",
    assignDelivery: "assignDelivery",
    detail: "detail",
    order: "order",
    secret: "secret",
    unlock: "unlock",
    icon: "icon",
    recharge: "recharge",
    cancelOrRefund: "cancel/refund",
    showOrHide: "show/hide",
    Variant: "Variant",
};