export const base_url = "http://localhost:8080";
//export const base_url = "http://admin.boozemart.bsconsultants.us";

export const apis = {
    base:"/api/v1",
    
    admin: "/admin",

    home: "/dashboard",
    roles: "/roles",
    subAdminList: "/sub-admin",
    taxList: "/tax",
    idList: "/id",
    membershipList: "/membership",
    reportItemSaleByStore: "/report/item-sale/by-store",
    reportItemSaleByTodayStore: "/report/required/itemlist/today/store",
    reportTotalItemSalesLast30Days: "/report/total-item-sales/last-30-days",
    reportTotalItemSalesLast30DaysDet: "/report/total-item-sales/last-30-days/det",
    reportTopDeliveryBoy: "/report/dboy-top",
    reportDeliveryBoy: "/report/dboy",
    reportTopStore: "/report/store-top",
    reportStore: "/report/store",
    reportTopUser: "/report/user-top",
    reportUser: "/report/user",
    reportTax: "/report/tax",
    driversForNotification: "/drivers-for-notification",
    storesForNotification:"/stores-for-notification",
    usersForNotification: "/users-for-notification",
    notificationListDriver: "/notification/driver",
    notificationListStore: "/notification/store",
    notificationListUser: "/notification/user",
    userList: "/user",
    userDetail: "/user/detail",
    usersWalletRechargeHistory: "/users/wallet-recharge-history",
    categoryList: "/category",
    categoryListAll: "/category/all",
    subCategoryList: "/sub-category",
    productList: "/product",
    productVarient: "/product/varient",
    bulkUploadProduct: "/bulk/upload/product",
    bulkUploadVarient: "/bulk/upload/varient",
    bulkUploadCity: "/bulk/upload/city",
    bulkUploadSociety: "/bulk/upload/society",
    trendingSearchProduct: "/trending-search/product",
    trendingSearchProductSelected: "/trending-search/product/selected",
    storeProductsList: "/store-data",
    societyList: "/society",
    areaBulkUploadCitySociety: "/area-bulk-upload/city-society",
    cityList: "/city",
    storesWaitingForApprovalStoreList: "/stores/waiting-for-approval/store",
    storesFinance: "/stores/finance",
    adminStoreList: "/admin/store",
    adminDBoyStoreList: "/d-boy/store",
    adminStoreOrder: "/admin/store/order",
    adminAllOrders: "/admin/all-orders",
    adminCancelledOrders: "/admin/cancelled/orders",
    adminCompleteOrders: "/admin/complete-orders",
    adminOngoingOrders: "/admin/ongoing-orders",
    adminOutForDeliveryOrders: "/admin/out-for-delivery-orders",
    adminPaymentFailedOrders: "/admin/payment-failed-orders",
    adminPendingOrders: "/admin/pending-orders",
    ordersTodayAll: "/orders/today/all",
    storeMissedOrders: "/store/missed/orders",
    cancelledOrders: "/cancelled/orders",
    nearByStore: "/near-by-store",
    payoutReq: "/payout-req",
    prv: "/prv",
    redeem: "/redeem",
    reward: "/reward",
    dBoyList: "/d-boy",
    dBoyOrder: "/d-boy/orders",
    dBoyIncentive: "/d-boy-incentive",
    aboutUs: "/about-us",
    terms: "/terms",
    driverFeedbackList: "/driver-feedback",
    storeFeedbackList: "/store-feedback",
    userFeedbackList: "/user-feedback",
    driverCallbackRequests: "/driver-callback-requests",
    storeCallbackRequests: "/store-callback-requests",
    userCallbackRequests: "/user-callback-requests",
    cancellingReasonsList: "/cancelling-reasons",

    logo: "/logo",
    countryCode: "/country-code",
    currency: "/currency",
    fcm: "/fcm",
    timeSlot: "/time-slot",
    minSetting: "/min-setting",
    msg91: "/msg91",
    twilio: "/twilio",
    sms: "/sms",
    firebase: "/firebase",
    firebaseIso: "/firebase-iso",
    settings: "/settings",
    mapApi: "/map-api",
    mapBox: "/map-box",
    mapSetting: "/map-setting",
    appNotice: "/app-notice",
    referral: "/referral-points",
    incentive: "/admin-driver-incentive",
    userNotNull: "/user-not-null",
    userNotNull2: "/user-not-null-2",
    appLink: "/app-link",
    imageSpace: "/image-space"
};
